version: '3.4'

services:
    django:
      build: .
      container_name: urlshortener
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - 8000:8000
      volumes:
        - .:/usr/src/app/
      environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
        - CELERY_BROKER=redis://redis:6379/0
        - CELERY_BACKEND=redis://redis:6379/0
      depends_on:
        - redis
    celery:
      build: .
      command: 
        - celery  -A urlshortener worker -l INFO
        - celery -A urlshortener beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler 
      volumes:
        - .:/usr/src/app/
      depends_on:
        - django
        - redis
    redis: 
      image: "redis:alpine"
