# Generated by Django 4.2.4 on 2023-08-07 07:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inUrl', models.URLField(verbose_name="Kısaltmak istediğiniz URL'yi girin")),
                ('outSlug', models.SlugField(unique=True)),
                ('timer', models.IntegerField(default=1, verbose_name="Kısa URL'niz kaç gün aktif olsun")),
                ('isActive', models.BooleanField(default=1)),
                ('dateStarted', models.DateTimeField(default=datetime.datetime(2023, 8, 7, 7, 47, 52, 395705, tzinfo=datetime.timezone.utc))),
                ('isPublic', models.BooleanField(default=1, verbose_name="URL'niz herkese açık olsun mu")),
                ('allowedUsers', models.ManyToManyField(related_name='allowed', to=settings.AUTH_USER_MODEL)),
                ('ownerUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
