# Generated by Django 4.2.3 on 2023-07-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inUrl', models.URLField()),
                ('outUrl', models.URLField()),
            ],
        ),
    ]
