# Generated by Django 4.2.3 on 2023-07-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='outUrl',
            field=models.SlugField(unique=True),
        ),
    ]
