# Generated by Django 4.2.3 on 2023-07-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0002_alter_urls_outurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='outUrl',
            new_name='outSlug',
        ),
    ]
