# Generated by Django 4.2.4 on 2023-08-31 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0002_alter_urls_datestarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='expirationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
