# Generated by Django 4.2.3 on 2023-07-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0003_rename_outurl_urls_outslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='timer',
            field=models.IntegerField(default=1),
        ),
    ]
