# Generated by Django 4.2.3 on 2023-07-31 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0004_urls_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('userEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='urls',
            name='dateStarted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 11, 42, 55, 881288, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='urls',
            name='isActive',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='urls',
            name='isPublic',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='urls',
            name='allowedUsers',
            field=models.ManyToManyField(to='shortenerapp.users'),
        ),
    ]
