# Generated by Django 4.2.4 on 2023-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0004_alter_urls_expirationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('mailtext', models.TextField(default='')),
                ('sendingDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='urls',
            name='expirationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
