# Generated by Django 4.2.3 on 2023-07-31 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0005_users_urls_datestarted_urls_isactive_urls_ispublic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='dateStarted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 11, 48, 35, 217754, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='urls',
            name='isPublic',
            field=models.BooleanField(default=1),
        ),
    ]
