# Generated by Django 4.2.3 on 2023-07-31 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0006_alter_urls_datestarted_alter_urls_ispublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='dateStarted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 12, 6, 52, 879921, tzinfo=datetime.timezone.utc)),
        ),
    ]
