# Generated by Django 4.2.4 on 2023-09-01 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import shortenerapp.enums


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('shortenerapp', '0008_alter_sendmail_sendingdate_alter_urls_expirationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default=shortenerapp.enums.SendMailStatus['active'], enum_class=shortenerapp.enums.SendMailStatus, max_length=8),
        ),
        migrations.AddField(
            model_name='sendmail',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='sendmail',
            name='sendingDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 8, 58, 39, 33038)),
        ),
        migrations.AlterField(
            model_name='urls',
            name='expirationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 1, 8, 58, 39, 31214)),
        ),
    ]
