# Generated by Django 4.2.3 on 2023-07-31 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0009_alter_urls_datestarted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='MyUsers',
        ),
        migrations.AlterField(
            model_name='urls',
            name='dateStarted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 12, 33, 50, 42199, tzinfo=datetime.timezone.utc)),
        ),
    ]
