# Generated by Django 4.2.4 on 2023-09-04 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0009_sendmail_status_sendmail_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmail',
            name='sendingDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 7, 22, 50, 137511)),
        ),
        migrations.AlterField(
            model_name='urls',
            name='expirationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 4, 7, 22, 50, 135803)),
        ),
    ]
