# Generated by Django 4.2.4 on 2023-09-04 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0010_alter_sendmail_sendingdate_alter_urls_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmail',
            name='sendingDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 7, 32, 48, 749464)),
        ),
        migrations.AlterField(
            model_name='urls',
            name='expirationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 4, 7, 32, 48, 745893)),
        ),
    ]
