# Generated by Django 4.2.3 on 2023-07-31 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0010_rename_users_myusers_alter_urls_datestarted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='dateStarted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 12, 42, 37, 388436, tzinfo=datetime.timezone.utc)),
        ),
    ]
