# Generated by Django 4.2.4 on 2023-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0013_alter_sendmail_sendingdate_alter_urls_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='expirationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
