# Generated by Django 4.2.4 on 2023-09-04 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0014_alter_urls_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='expirationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 4, 10, 50, 9, 489991)),
        ),
    ]
