# Generated by Django 4.2.4 on 2023-09-06 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerapp', '0018_alter_urls_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='expirationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 6, 11, 44, 5, 16825)),
        ),
    ]
